openapi: 3.0.4

info:
  title: Product APIs
  description: Product APIs for managing products
  version: 1.0.0
tags:
  - name: Product
    description: Product management APIs
paths:
  /api/v1/products:
    get:
      tags:
        - Product
      summary: Get all products
      operationId: getAllProducts
      responses:
        '200':
          description: Get all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
    post:
      tags:
        - Product
      summary: Create a new product
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Invalid request
  /api/v1/products/{productId}:
    get:
      tags:
        - Product
      summary: Get product by productId
      operationId: getProductById
      parameters:
        - $ref: '#/components/parameters/ProductId'
      responses:
        '200':
          description: Found prodct by productId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '404':
          description: Product did not found
    put:
      tags:
        - Product
      summary: Replace product
      operationId: updateProduct
      parameters:
        - $ref: '#/components/parameters/ProductId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Invalid request
        '404':
          description: Product did not found
    patch:
      tags:
        - Product
      summary: Partially update product
      operationId: patchProduct
      parameters:
        - $ref: '#/components/parameters/ProductId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchProductRequest'
      responses:
        '200':
          description: Product patched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Invalid request
        '404':
          description: Product did not found
    delete:
      tags:
        - Product
      summary: Delete product
      operationId: deleteProduct
      parameters:
        - $ref: '#/components/parameters/ProductId'
      responses:
        '204':
          description: Product deleted successfully
        '404':
          description: Product did not found
components:
  parameters:
    ProductId:
      name: productId
      in: path
      required: true
      description: Product Id
      schema:
        type: string
        format: uuid
        example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
  schemas:
    CreateProductRequest:
      type: object
      required:
        - name
        - price
        - quantity
      properties:
        name:
          type: string
          example: Laptop
        description:
          type: string
          example: Gaming laptop
        price:
          type: number
          format: double
          example: 1200.50
        quantity:
          type: integer
          format: int64
          example: 10
    ProductResponse:
      type: object
      properties:
        productId:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        name:
          type: string
          example: Laptop
        description:
          type: string
          example: Gaming laptop
        price:
          type: number
          format: double
          example: 1200.50
        quantity:
          type: integer
          format: int64
          example: 10
        createdAt:
          type: string
          format: date-time
          example: 2026-06-19T12:30:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2026-06-19T13:00:00Z
    UpdateProductRequest:
      type: object
      required:
        - name
        - price
        - quantity
      properties:
        name:
          type: string
          example: Laptop Pro
        description:
          type: string
          example: Updated gaming laptop
        price:
          type: number
          format: double
          example: 1350.00
        quantity:
          type: integer
          format: int64
          example: 5
    PatchProductRequest:
      type: object
      properties:
        name:
          type: string
          example: Laptop Pro
        description:
          type: string
          example: Updated description
        price:
          type: number
          format: double
          example: 1300.00
        quantity:
          type: integer
          format: int64
          example: 7
